services:

  joomla:
    image: joomla
    container_name: joomla    
    restart: unless-stopped
    depends_on:
      - joomladb
    ports:
      - "8200:80"
    volumes:
      - ./html:/var/www/html
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: p4ssw0rd

  joomladb:
    image: mysql:latest
    container_name: joomladb    
    expose:
      - "3306"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: joomlapma 
    restart: unless-stopped
    environment:
      PMA_ARBITRARY: "1"
    ports:
      - "8080:80"


