services:

  joomla:
    image: joomla:latest
    container_name: joomla    
    restart: unless-stopped
    ports:
      - "8200:80"
    depends_on:
      - joomladb
    volumes:
      - ./joomla/data:/var/www/html
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_NAME: joomla_db
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: p4ssw0rd

  joomladb:
    image: mysql:latest
    container_name: joomladb    
    expose:
      - "3306"
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: joomla_db
      MYSQL_USER: joomla
      MYSQL_PASSWORD: p4ssw0rd
      MYSQL_ROOT_PASSWORD: p4ssw0rd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: joomlapma 
    restart: unless-stopped
    environment:
      PMA_ARBITRARY: "1"
    ports:
      - "8080:80"
