services:

  joomla:
    image: joomla:latest
    restart: unless-stopped
    ports:
      - "8200:80"
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: examplepass
      JOOMLA_DB_NAME: joomla_db
      JOOMLA_SITE_NAME: Joomla
      JOOMLA_ADMIN_USER: Admin
      JOOMLA_ADMIN_USERNAME: admin
      JOOMLA_ADMIN_PASSWORD: p4ssw0rd-1234
      JOOMLA_ADMIN_EMAIL: admin@example.com
    volumes:
      - ./joomla_data:/var/www/html

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: joomla_db
      MYSQL_USER: joomla
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db_data:/var/lib/mysql
